AndrewStoddardVacationPlanner/Models/ViewModels/ManageViewModel.cs
// ***********************************************************************
// Author           : Incendy
// Created          : 04-08-2021
//
// Last Modified By : Incendy
// Last Modified On : 04-08-2021
// ***********************************************************************

using System.Collections.Generic;
using AndrewStoddardVacationPlanner.Models.DomainModels;

namespace AndrewStoddardVacationPlanner.Models.ViewModels
{
    /// <summary>
    ///     Class ManageViewModel.
    /// </summary>
    public class ManageViewModel
    {
        #region Properties

        /// <summary>
        ///     Gets or sets the name of the accommodation.
        /// </summary>
        /// <value>The name of the accommodation.</value>
        public string AccommodationName { get; set; }

        /// <summary>
        ///     Gets or sets the accommodation email.
        /// </summary>
        /// <value>The accommodation email.</value>
        public string AccommodationEmail { get; set; }

        /// <summary>
        ///     Gets or sets the accommodation phone.
        /// </summary>
        /// <value>The accommodation phone.</value>
        public string AccommodationPhone { get; set; }

        /// <summary>
        ///     Gets or sets the name of the activity.
        /// </summary>
        /// <value>The name of the activity.</value>
        public string ActivityName { get; set; }

        /// <summary>
        ///     Gets or sets the name of the destination.
        /// </summary>
        /// <value>The name of the destination.</value>
        public string DestinationName { get; set; }

        /// <summary>
        ///     Gets or sets the destinations.
        /// </summary>
        /// <value>The destinations.</value>
        public List<Destination> Destinations { get; set; }

        /// <summary>
        ///     Gets or sets the activities.
        /// </summary>
        /// <value>The activities.</value>
        public List<Activity> Activities { get; set; }

        /// <summary>
        ///     Gets or sets the accommodations.
        /// </summary>
        /// <value>The accommodations.</value>
        public List<Accommodation> Accommodations { get; set; }

        /// <summary>
        ///     Gets or sets the selected activity to delete.
        /// </summary>
        /// <value>The selected activity to delete.</value>
        public int SelectedActivityToDelete { get; set; }

        /// <summary>
        ///     Gets or sets the selected accommodation to delete.
        /// </summary>
        /// <value>The selected accommodation to delete.</value>
        public int SelectedAccommodationToDelete { get; set; }

        /// <summary>
        ///     Gets or sets the selected destination to delete.
        /// </summary>
        /// <value>The selected destination to delete.</value>
        public int SelectedDestinationToDelete { get; set; }

        #endregion
    }
}

AndrewStoddardVacationPlanner/Controllers/VacationController.cs
// ***********************************************************************
// Author           : Incendy
// Created          : 04-08-2021
//
// Last Modified By : Incendy
// Last Modified On : 04-08-2021
// ***********************************************************************

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using AndrewStoddardVacationPlanner.Models.DataAccessLayer;
using AndrewStoddardVacationPlanner.Models.DomainModels;
using AndrewStoddardVacationPlanner.Models.Enums;
using AndrewStoddardVacationPlanner.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AndrewStoddardVacationPlanner.Controllers
{
    /// <summary>
    ///     Class VacationController.
    ///     Implements the <see cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class VacationController : Controller
    {
        #region Data members

        /// <summary>
        ///     The unit of work
        /// </summary>
        private readonly IUnitOfWork unitOfWork;

        /// <summary>
        ///     The HTTP context accessor
        /// </summary>
        private readonly IHttpContextAccessor httpContextAccessor;

        #endregion

        #region Constructors

        /// <summary>
        ///     Initializes a new instance of the <see cref="VacationController" /> class.
        /// </summary>
        /// <param name="unitOfWork">The unit of work.</param>
        /// <param name="httpContextAccessor">The HTTP context accessor.</param>
        public VacationController(IUnitOfWork unitOfWork, IHttpContextAccessor httpContextAccessor)
        {
            this.unitOfWork = unitOfWork;
            this.httpContextAccessor = httpContextAccessor;
        }

        #endregion

        #region Methods

        /// <summary>
        ///     Homes the specified page number.
        /// </summary>
        /// <param name="pageNumber">The page number.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Home(int pageNumber = 1)
        {
            var pageSize = this.httpContextAccessor.HttpContext.Session.GetInt32("page_size") ?? 2;
            var trips = this.unitOfWork.Trips.Get().Include(t => t.Activities).Include(t => t.Destination)
                            .Include(t => t.Accommodation).ToList();
            if (this.httpContextAccessor.HttpContext.Session.GetInt32("sort_direction") ==
                (int) SortDirection.Ascending)
            {
                trips = this.orderAscending(trips);
            }
            else if (this.httpContextAccessor.HttpContext.Session.GetInt32("sort_direction") ==
                     (int) SortDirection.Descending)
            {
                trips = this.orderDescending(trips);
            }

            var totalPages = trips.Count / pageSize;
            totalPages += trips.Count % pageSize == 0 ? 0 : 1;
            trips = trips.Skip((pageNumber - 1) * pageSize).Take(pageSize > trips.Count ? trips.Count : pageSize)
                         .ToList();

            var viewModel = new VacationListViewModel {
                PageNumber = pageNumber,
                PageSize = pageSize,
                TotalPages = totalPages,
                Trips = trips
            };

            return View(viewModel);
        }

        /// <summary>
        ///     Adds the trip step1.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult AddTripStep1()
        {
            ViewBag.Destinations = this.unitOfWork.Destinations.Get().ToList();
            ViewBag.Accommodations = this.unitOfWork.Accommodations.Get().ToList();

            return View();
        }

        /// <summary>
        ///     Manages this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Manage()
        {
            return View(this.setupManageViewModel());
        }

        /// <summary>
        ///     Deletes the trip.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult DeleteTrip(int id)
        {
            var trip = this.unitOfWork.Trips.Get().Include(t => t.Destination).FirstOrDefault(t => t.Id == id);
            this.unitOfWork.Trips.Delete(trip);
            this.unitOfWork.Save();
            TempData["message"] = $"Deleted trip to {trip.Destination.Name} on {trip.StartDate.ToShortDateString()}.";
            return RedirectToAction("Home");
        }

        /// <summary>
        ///     Orders the descending.
        /// </summary>
        /// <param name="trips">The trips.</param>
        /// <returns>List&lt;Trip&gt;.</returns>
        private List<Trip> orderDescending(List<Trip> trips)
        {
            trips = this.httpContextAccessor.HttpContext.Session.GetInt32("sort_type") switch {
                1 => trips.OrderBy(trip => trip.Destination.Name).ToList(),
                2 => trips.OrderBy(trip => trip.StartDate).ToList(),
                3 => trips.OrderBy(trip => trip.EndDate).ToList(),
                4 => trips.OrderBy(trip => trip.Accommodation.Name).ToList(),
                5 => trips.OrderBy(trip => trip.Activities.Count).ToList()
            };
            return trips;
        }

        /// <summary>
        ///     Orders the ascending.
        /// </summary>
        /// <param name="trips">The trips.</param>
        /// <returns>List&lt;Trip&gt;.</returns>
        private List<Trip> orderAscending(List<Trip> trips)
        {
            trips = this.httpContextAccessor.HttpContext.Session.GetInt32("sort_type") switch {
                1 => trips.OrderByDescending(trip => trip.Destination.Name).ToList(),
                2 => trips.OrderByDescending(trip => trip.StartDate).ToList(),
                3 => trips.OrderByDescending(trip => trip.EndDate).ToList(),
                4 => trips.OrderByDescending(trip => trip.Accommodation.Name).ToList(),
                5 => trips.OrderByDescending(trip => trip.Activities.Count).ToList()
            };
            return trips;
        }

        /// <summary>
        ///     Pages the size.
        /// </summary>
        /// <param name="size">The size.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        public IActionResult PageSize(int size)
        {
            this.httpContextAccessor.HttpContext.Session.SetInt32("page_size", size);
            return RedirectToAction("Home");
        }

        /// <summary>
        ///     Sorts the specified sort.
        /// </summary>
        /// <param name="sort">The sort.</param>
        /// <returns>IActionResult.</returns>
        public IActionResult Sort(SortType sort)
        {
            this.httpContextAccessor.HttpContext.Session.SetInt32("sort_type", (int) sort);
            if (this.httpContextAccessor.HttpContext.Session.GetInt32("sort_direction") ==
                (int) SortDirection.Ascending)
            {
                this.httpContextAccessor.HttpContext.Session.SetInt32("sort_direction", (int) SortDirection.Descending);
            }
            else
            {
                this.httpContextAccessor.HttpContext.Session.SetInt32("sort_direction", (int) SortDirection.Ascending);
            }

            return RedirectToAction("Home");
        }

        /// <summary>
        ///     Adds the trip step2.
        /// </summary>
        /// <param name="trip">The trip.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        public IActionResult AddTripStep2(Trip trip)
        {
            if (ModelState.IsValid)
            {
                TempData["trip_dest"] = trip.DestinationId;
                TempData["trip_acc"] = trip.AccommodationId;
                TempData["trip_start"] = trip.StartDate;
                TempData["trip_end"] = trip.EndDate;
                ViewBag.Activities = this.unitOfWork.Activities.Get().ToList();

                return View();
            }

            ViewBag.Destinations = this.unitOfWork.Destinations.Get().ToList();
            ViewBag.Accommodations = this.unitOfWork.Accommodations.Get().ToList();
            return View("AddTripStep1", trip);
        }

        /// <summary>
        ///     Adds the trip.
        /// </summary>
        /// <param name="activities">The activities.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        public IActionResult AddTrip(int[] activities)
        {
            var trip = new Trip {
                DestinationId = (int) TempData["trip_dest"],
                AccommodationId = (int) TempData["trip_acc"],
                StartDate = (DateTime) TempData["trip_start"],
                EndDate = (DateTime) TempData["trip_end"]
            };
            trip.Activities = new List<Activity>();
            foreach (var activityid in activities)
            {
                trip.Activities.Add(this.unitOfWork.Activities.Get().FirstOrDefault(a => a.Id == activityid));
            }

            this.unitOfWork.Trips.Insert(trip);
            this.unitOfWork.Save();

            TempData["message"] =
                $"Trip for {this.unitOfWork.Destinations.Get().FirstOrDefault(t => t.Id == trip.DestinationId).Name} on {trip.StartDate.ToShortDateString()}";

            return RedirectToAction("Home");
        }

        /// <summary>
        ///     Adds from manage.
        /// </summary>
        /// <param name="viewModel">The view model.</param>
        /// <returns>IActionResult.</returns>
        [HttpPost]
        public IActionResult AddFromManage(ManageViewModel viewModel)
        {
            if (string.IsNullOrEmpty(viewModel.AccommodationName) &&

AndrewStoddardVacationPlanner/Views/Vacation/AddTripStep1.cshtml
@model Trip
@{
    ViewData["Title"] = "Add Trip";
}
<div class="container">
    <form class="form-group" asp-action="AddTripStep2" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>

        <label>Destination: </label>
        <select class="form-control" asp-for="DestinationId" asp-items="@(new SelectList(ViewBag.Destinations, "Id","Name"))"></select>

        <label>Accommodation: </label>
        <select class="form-control" asp-for="AccommodationId" asp-items="@(new SelectList(ViewBag.Accommodations, "Id","Name"))"></select>

        <label>Start: </label>
        <input class="form-control" asp-for="StartDate" />

        <label>End: </label>
        <input class="form-control m-1" asp-for="EndDate" />

        <button type="submit" class="btn btn-primary m-1">Next</button>
        <a class="btn btn-primary" asp-action="Home">Cancel</a>
    </form>
</div>

AndrewStoddardVacationPlanner/Views/Vacation/AddTripStep2.cshtml
@{
    ViewData["Title"] = "Add Trip";
}
<div class="container">
    <form class="form-group" asp-action="AddTrip" method="post">
        <div asp-validation-summary="All" class="text-danger"></div>

        <label>Activities: </label>
        <select class="form-control" multiple="multiple" name="activities" asp-items="@(new MultiSelectList(ViewBag.Activities, "Id","Name"))"></select>

        <button type="submit" class="btn btn-primary m-1">Save</button>
        <a class="btn btn-primary" asp-action="Home">Cancel</a>
    </form>
</div>

AndrewStoddardVacationPlanner/Views/Vacation/Home.cshtml
@model VacationListViewModel
@{
    ViewData["Title"] = "Home Page";
}
<div class="container-fluid">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    <a asp-action="Sort" asp-route-sort="SortByDestination">Destination</a>
                </th>
                <th>
                    <a asp-action="Sort" asp-route-sort="SortByStartDate">Start Date</a>
                </th>
                <th>
                    <a asp-action="Sort" asp-route-sort="SortByEndDate">End Date</a>
                </th>
                <th>
                    <a asp-action="Sort" asp-route-sort="SortByAccommodation">Accommodation</a>
                </th>
                <th>
                    <a asp-action="Sort" asp-route-sort="SortByActivities">Activities</a>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Trip trip in Model.Trips)
            {
                <tr>
                    <td>
                        @trip.Destination.Name
                    </td>
                    <td>
                        @trip.StartDate.ToShortDateString()
                    </td>
                    <td>
                        @trip.EndDate.ToShortDateString()
                    </td>
                    <td>
                        @trip.Accommodation.Name
                    </td>
                    <td>
                        @foreach (Activity activity in trip.Activities)
                        {
                            <p>@($"{activity.Name} \n") </p>
                        }
                    </td>
                    <td>
                        <a class="btn btn-outline-danger" asp-action="DeleteTrip" asp-route-id="@trip.Id">Delete</a>
                    </td>
                </tr>

                
            }
        </tbody>
    </table>
</div>
<div class="container-fluid m-2">
    @for (int i = 1; i <= Model.TotalPages; i++)
    {
        <a asp-action="Home" asp-controller="Vacation" asp-route-pageNumber="@i" class="btn btn-outline-primary @(Model.PageNumber == i ? "active" : "")">@i</a>
    }
</div>
<div class="container-fluid m-2">
    <form class="form-inline" asp-action="PageSize" method="post">
        <label>Page Size: </label>
        <select class="form-control m-2" name="size" asp-items="@(new SelectList(Model.PageSizes, Model.PageSize))">
        </select>

        <button type="submit" class="btn btn-primary m-1">Apply</button>
    </form>
</div>

AndrewStoddardVacationPlanner/Views/Vacation/Manage.cshtml
@model ManageViewModel
@{
    ViewData["Title"] = "Manage";
}
<div class="container-fluid text-center">
    <h1>Manage Destinations, Accommidations, and Activities</h1>
</div>
<div class="row">
    <div class="col container-fluid">
        <h2>Add</h2>
        <form class="form-group" asp-action="AddFromManage" method="post">
            <div class="form-group border p-2">
                <label>Destination:</label>
                <input class="form-control" asp-for="DestinationName" />
            </div>

            <div class="form-group border p-2">
                <label>Accommodation Name:</label>
                <input class="form-control" asp-for="AccommodationName" />
                <label>Accommodation Email:</label>
                <input class="form-control" asp-for="AccommodationEmail" />
                <label>Accommodation Phone:</label>
                <input class="form-control" asp-for="AccommodationPhone" />
            </div>

            <div class="form-group border p-2">
                <label>Activity:</label>
                <input class="form-control" asp-for="ActivityName" />
            </div>
            <button type="submit" class="btn btn-primary m-1">Add</button>
            <input type="hidden" asp-for="Destinations" />
            <input type="hidden" asp-for="Accommodations" />
            <input type="hidden" asp-for="Activities" />
        </form>
    </div>
    <div class="col container-fluid">
        <h2>Delete</h2>
        <form class="form-group" asp-action="DeleteFromManage" method="post">
            <div class="form-group border p-2">
                <label>Destination:</label>
                <select class="form-control" asp-for="SelectedDestinationToDelete" asp-items="@(new SelectList(Model.Destinations, "Id", "Name"))">
                    <option value="0"></option>
                </select>
            </div>
            <div class="form-group border p-2">
                <label>Accommodation:</label>
                <select class="form-control" asp-for="SelectedAccommodationToDelete" asp-items="@(new SelectList(Model.Accommodations, "Id", "Name"))">
                    <option value="0"></option>
                </select>
            </div>
            <div class="form-group border p-2">
                <label>Activity:</label>
                <select class="form-control" asp-for="SelectedActivityToDelete" asp-items="@(new SelectList(Model.Activities, "Id", "Name"))">
                    <option value="0"></option>
                </select>
            </div>
            <input type="hidden" asp-for="Destinations" />
            <input type="hidden" asp-for="Accommodations" />
            <input type="hidden" asp-for="Activities" />

            <button type="submit" class="btn btn-primary m-1">Delete</button>
        </form>
    </div>
</div>